import "bootstrap/dist/css/bootstrap.min.css";
import styles from "../../scss/font.scss";
import Header from "./Header"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="styles">
        <Header />
        {children}
      </body>
    </html>
  );
}
